### PR TITLE
Create the nethserver-fail2ban group comps

### PR DESCRIPTION
**Pull request by stephdl**
https://github.com/NethServer/dev/issues/5489

@DavidePrincipi I cannot add you as reviewer

### CODE REVIEW

**Comment by stephdl** [comment]
simple
* without `whois`

```

Hi,

The IP 125.212.248.37 has just been banned by Fail2Ban after
3 attempts against sshd.


Here is more information about 125.212.248.37 :

missing whois program

Regards,

Fail2Ban

```

* with `whois` 

```
Hi,

The IP 1.214.34.114 has just been banned by Fail2Ban after
3 attempts against sshd.


Here is more information about 1.214.34.114 :

% [whois.apnic.net]
% Whois data copyright terms    http://www.apnic.net/db/dbcopyright.html

% Information related to '1.208.0.0 - 1.223.255.255'

% Abuse contact for '1.208.0.0 - 1.223.255.255' is 'hostmaster@nic.or.kr'

inetnum:        1.208.0.0 - 1.223.255.255
netname:        BORANET
descr:          LG DACOM Corporation
admin-c:        IM646-AP
tech-c:         IM646-AP
country:        KR
status:         ALLOCATED PORTABLE
mnt-by:         MNT-KRNIC-AP
mnt-irt:        IRT-KRNIC-KR
last-modified:  2017-02-03T00:54:59Z
source:         APNIC

irt:            IRT-KRNIC-KR
address:        Seocho-ro 398, Seocho-gu, Seoul, Korea
e-mail:         hostmaster@nic.or.kr
abuse-mailbox:  hostmaster@nic.or.kr
admin-c:        IM574-AP
tech-c:         IM574-AP
auth:           # Filtered
mnt-by:         MNT-KRNIC-AP
last-modified:  2017-10-19T07:36:36Z
source:         APNIC

person:         IP Manager
address:        Seoul Yongsan-gu Hangang-daero 32
country:        KR
phone:          +82-2-10-1
e-mail:         ipadm@lguplus.co.kr
nic-hdl:        IM646-AP
mnt-by:         MNT-KRNIC-AP
last-modified:  2017-08-07T01:06:21Z
source:         APNIC

% Information related to '1.208.0.0 - 1.223.255.255'

inetnum:        1.208.0.0 - 1.223.255.255
netname:        BORANET-KR
descr:          LG DACOM Corporation
country:        KR
admin-c:        IA5-KR
tech-c:         IA5-KR
status:         ALLOCATED PORTABLE
mnt-by:         MNT-KRNIC-AP
mnt-irt:        IRT-KRNIC-KR
remarks:        This information has been partially mirrored by APNIC from
remarks:        KRNIC. To obtain more specific information, please use the
remarks:        KRNIC whois server at whois.krnic.net.
changed:        hostmaster@nic.or.kr
source:         KRNIC

person:         IP Manager
address:        Seoul Yongsan-gu Hangang-daero 32
address:        LG UPLUS
country:        KR
phone:          +82-2-10-1
e-mail:         ipadm@lguplus.co.kr
nic-hdl:        IA5-KR
mnt-by:         MNT-KRNIC-AP
changed:        hostmaster@nic.or.kr
source:         KRNIC

% This query was served by the APNIC Whois Service version 1.88.15-46 (WHOIS-UK3)

Regards,

Fail2Ban
```

**Comment by gsanchietti** [comment]
I'd add it as required .

**Comment by stephdl** [comment]
The report is quite long and could  add some load to tiny sever, I'd prefer to be optional

**Comment by stephdl** [comment]
@DavidePrincipi @gsanchietti no permission to merge this, if you agree, please do it

**Comment by DavidePrincipi** [comment]
I'll merge it when NethServer/dev#5489 is closed

**Pull request merged**
